### ISSUE TITLE
Enhancement for IGUANA configurations

### ISSUE THREAD

**Issue by tohardik** [dice-group/IGUANA#117]
Allow referencing of values already defined in the configuration.
e.g.

```
const:
    predef_const:
        timeLimit: 15
        queryHandler: "taskx.queryHandler"
        workers: sparql4
task8:
    constructorArgs: const.predef_const
```

Currently, the way configurations are loaded in the application, it does not allow this kind of references. So reading the value for 'task8. constructorArgs' would yield string 'const.predef_const'. But instead, it should yield the object already defined above. 

Approach: This can be done with recursively reading the properties.
