### ISSUE TITLE
RabbitMQ connection error in docker composition

### ISSUE THREAD

**Issue by abourdon** [dice-group/IGUANA#81]
Hi,

I would like to simply run Iguana, then I used the [docker-compose.yml](https://github.com/dice-group/IGUANA/blob/master/docker-compose.yml) file from the root folder.

Unfortunately, the connection between the Result Processor and RabbitMQ seems to not work well :

<img width="1015" alt="screen shot 2017-12-04 at 10 47 59" src="https://user-images.githubusercontent.com/1511715/33546283-e656316c-d8e0-11e7-8807-a26dc76275bd.png">

However, RabbitMQ is reachable through my docker host port at 8081:

![screen shot 2017-12-04 at 10 55 50](https://user-images.githubusercontent.com/1511715/33546603-be1615e0-d8e1-11e7-9779-27c91a46fb0e.png)

Note I'm using a slightly different version of the official `docker-compose`, because it actually uses a predefined external network which I have not information about. Hereafter the docker-compose I'm using:

```
version: '3'
services:
  # message bus
  rabbit:
    image: rabbitmq:management
    ports:
     - "8081:15672"
     # Forwarding the port for testing
     - "5672:5672"

  web:
    image: iguana/webcontroller
    ports: 
     - "8085:8085"
    environment:
     - IP=0.0.0.0
     - RABBIT_HOST=rabbit
    depends_on:
     - rabbit


  result-processor:
    image: iguana/resultprocessor:live
    ports: 
     - "9999:9999"
    environment:
     - RABBIT_HOST=rabbit
    depends_on:
     - rabbit
``` 

Any clue about this?

Regards,
Aurélien

**Comment by TortugaAttack** [comment]
Hey,
It seems that the docker container cannot connect to each other (the network is missing)

Can you do the following:

`docker network create iguana`
and add the network part again
```
networks:
  iguana:
    external:
name: iguana
```
and test again?

This should do the trick.
